### ISSUE TITLE
Setting own template by typoscript does not work!

### ISSUE THREAD

**Issue by fisruk** [fabarea/rss_display#2]
plugin.tx_rssdisplay {
  settings {
    templates {
      rss_display_custom {
        label = Angepasstes Template                                
        path = _res/Components/RSSDisplay/Resources/Private/Templates/Feed/Show.html
      }
      rss_display_1 > 
      rss_display_2 >
      rss_display_3 >
    }
  }
}

TypoScript is checked in typoscript-object-browser. The settings are shown correct in the object-browser. The content element ignores the settings.

Dirty fix is tho change in the setup.txt in the plugin directory.

**Comment by johlton** [comment]
I can confirm this. BE does not reflect TS changes.

**Comment by fabarea** [comment]
I just double checked with latest version of EXT:rss_display and CMS 7 and it has worked for me as expected (menu in TCEForm is well updated). I added the config in the setup.txt as follows. Can you re-try and let me know?

```
# Plugin configuration
plugin.tx_rssdisplay {
  settings {

    templates {
      rss_display_4 {
        label = HELLO HELLO
        path = EXT:rss_display/Resources/Private/Templates/Feed/ShowWithoutDescription.html
      }
    }
  }
}
```

**Comment by oft-test-account** [comment]
Hello,

we still have the problem as described above. Typo3 version is 7.6.9 /  	fluidcontent_core 1.4.0

The config looks like this:

```
plugin.tx_rssdisplay {
      settings {
            templates {
                or_rss {
                    label = Mein RSS Feed 
                    path = EXT:my_extension/Resources/Private/Templates/Extensions/Feed/custom-template.html
                 }
             }
       }
  }
```

The setting in the object-browser are ok - no problems here. Maybe there is another workaround apart from modifying the setup.txt in the plugin directory directly?

Help appreciated :-)

Kind regards

**Comment by wegewerk-mkb** [comment]
Since the Typoscript is added in the ext_localconf.php the only way to make sure your custom Typoscript is loaded later is to define rss_display as a dependeny in the ext_emconf.php

Still, that won't help since the TceForms Class is broken and will not select any template path, leading to the fallback `$this->settings['template'] = 'EXT:rss_display/Resources/Private/Templates/Feed/Show.html';`

As far as I can tell the parameter `$row` is unused and so `$params` is always empty.
https://github.com/fabarea/rss_display/blob/f7e02a39ae68f74a0e0b65ea114b02a6912e9da0/Classes/Backend/TceForms.php#L30

**Comment by sksksksk** [comment]
I have the same problem and haven't figured out how to work around it yet.
The only thing that works for me is to add the relevant Typoscript into the setup.txt of the extension itself.
